"""
Constants Package - Organized configuration values for level generation

Separates constants into logical categories for better organization:
- maze: Maze generation parameters
- decoration: Platform, pillar, and hole generation
- entities: Hazards and pickup spawn rates
- abilities: Ability system configuration
"""

from .maze import (
    DEFAULT_VERTICALITY_BIAS,
    DEFAULT_BRANCHINESS,
)

from .decoration import (
    DEFAULT_PLATFORM_BAND_STEP,
    DEFAULT_PLATFORM_LEN_RANGE,
    DEFAULT_PILLAR_CHANCE,
    DEFAULT_HOLE_CHANCE,
    ROOM_FLOOR_OFFSET,
)

from .entities import (
    DEFAULT_HAZARD_RATE,
    DEFAULT_COIN_DENSITY,
    DEFAULT_HEALTH_DENSITY,
    DEFAULT_LIVES_PER_LEVEL,
    DEFAULT_POWERUP_DENSITY,
    HAZARD_SAFE_RADIUS,
    MAX_SPAWN_ATTEMPTS,
)

from .abilities import (
    DEFAULT_ABILITY_ORB_SPAWN_RATE,
    DEFAULT_PHASEABLE_WALL_CHANCE,
    DEFAULT_ENABLE_ABILITY_SUBROOMS,
    DEFAULT_SUBROOM_INTENSITY,
    DEFAULT_ENABLE_ABILITY_CHALLENGES,
    CHALLENGE_ATTEMPTS,
    SUBROOM_EMPTY_THRESHOLD,
)

__all__ = [
    # Maze
    'DEFAULT_VERTICALITY_BIAS',
    'DEFAULT_BRANCHINESS',
    # Decoration
    'DEFAULT_PLATFORM_BAND_STEP',
    'DEFAULT_PLATFORM_LEN_RANGE',
    'DEFAULT_PILLAR_CHANCE',
    'DEFAULT_HOLE_CHANCE',
    'ROOM_FLOOR_OFFSET',
    # Entities
    'DEFAULT_HAZARD_RATE',
    'DEFAULT_COIN_DENSITY',
    'DEFAULT_HEALTH_DENSITY',
    'DEFAULT_LIVES_PER_LEVEL',
    'DEFAULT_POWERUP_DENSITY',
    'HAZARD_SAFE_RADIUS',
    'MAX_SPAWN_ATTEMPTS',
    # Abilities
    'DEFAULT_ABILITY_ORB_SPAWN_RATE',
    'DEFAULT_PHASEABLE_WALL_CHANCE',
    'DEFAULT_ENABLE_ABILITY_SUBROOMS',
    'DEFAULT_SUBROOM_INTENSITY',
    'DEFAULT_ENABLE_ABILITY_CHALLENGES',
    'CHALLENGE_ATTEMPTS',
    'SUBROOM_EMPTY_THRESHOLD',
]
